# compiles all the files and creates corresponding executables:

all:
	gcc diceGame.c -pthread -o diceGame
	gcc multiplayerGameLobby.c -pthread -o multiplayerGameLobby
	gcc pipelineSimulation.c -pthread -o pipelineSimulation
	gcc weatherDataCollection.c -pthread -o weatherDataCollection


