all:
	gcc threadedSine.c -pthread -o threadedSine
	gcc globalVarThreadedSine.c -pthread -o globalVarThreadedSine
	gcc sineWithMutex.c -pthread -o sineWithMutex
	gcc sineWithSpinlock.c -pthread -o sineWithSpinlock
